export const GRAMMARS_MAP = new Map([
  ['html', 'text.html.basic'],
  ['haml', 'text.haml'],
  ['markdown', 'text.html.markdown'],
  ['pug', 'text.pug'],
  ['css', 'source.css'],
  ['less', 'source.css.less'],
  ['scss', 'source.css.scss'],
  ['sass', 'source.sass'],
  ['stylus', 'source.stylus'],
  ['postcss', 'source.postcss'],
  ['javascript', 'source.js'],
  ['typescript', 'source.ts'],
  ['coffeescript', 'source.coffee'],
  ['livescript', 'source.livescript'],
]);

export const COMMON_GRAMMARS_MAP = {
  babel: 'javascript',
} as const;

export const GRAMMAR_SCOPE_NAME_MAP = {
  'text.html.basic': 'html.tmLanguage.json',
  'text.html.markdown': 'markdown.tmLanguage.json',
  'text.html.handlebars': 'Handlebars.tmLanguage.json',
  'text.html.derivative': 'html-derivative.tmLanguage.json',
  'text.html.javadoc': 'JavaDoc.tmLanguage',
  'text.html.textile': 'Textile.tmLanguage',
  'text.haml': 'Ruby Haml.tmLanguage',
  'text.pug': 'pug.tmLanguage.json',
  'text.xml': 'xml.tmLanguage.json',
  'text.xml.xsl': 'xsl.tmLanguage.json',
  'text.git-commit': 'git-commit.tmLanguage.json',
  'text.git-rebase': 'git-rebase.tmLanguage.json',
  'text.log': 'log.tmLanguage.json',
  'text.dart-doccomments': 'Dart Doc Comments.tmLanguage',
  'text.elixir': 'Elixir.tmLanguage',
  'source.css': 'css.tmLanguage.json',
  'source.css.scss': 'scss.tmLanguage.json',
  'source.scss': 'scss.tmLanguage.json',
  'source.sass': 'Sass.tmLanguage',
  'source.sassdoc': 'sassdoc.tmLanguage.json',
  'source.css.less': 'less.tmLanguage.json',
  'source.less': 'less.tmLanguage.json',
  'source.stylus': 'Stylus.tmLanguage',
  'source.postcss': 'PostCSS.tmLanguage',
  'source.js': 'javascript.tmLanguage.json',
  'source.ts': 'typescript.tmLanguage.json',
  'source.coffee': 'coffeescript.tmLanguage.json',
  'source.livescript': 'LiveScript.tmLanguage',
  'source.js.regexp': 'Regular Expressions (JavaScript).tmLanguage',
  'source.ini': 'ini.tmLanguage.json',
  'source.java': 'java.tmLanguage.json',
  'source.lua': 'lua.tmLanguage.json',
  'source.makefile': 'make.tmLanguage.json',
  'source.perl': 'perl.tmLanguage.json',
  'source.r': 'r.tmLanguage.json',
  'source.ruby': 'ruby.tmLanguage.json',
  'source.ruby.rails': 'ruby.tmLanguage.json',
  'source.php': 'php.tmLanguage.json',
  'source.sql': 'sql.tmLanguage.json',
  'source.asp.vb.net': 'asp-vb-net.tmlanguage.json',
  'source.yaml': 'yaml.tmLanguage.json',
  'source.batchfile': 'batchfile.tmLanguage.json',
  'source.clojure': 'clojure.tmLanguage.json',
  'source.c': 'c.tmLanguage.json',
  'source.cpp': 'cpp.tmLanguage.json',
  'source.diff': 'diff.tmLanguage.json',
  'source.dockerfile': 'docker.tmLanguage.json',
  'source.go': 'go.tmLanguage.json',
  'source.groovy': 'groovy.tmLanguage.json',
  'source.json': 'JSON.tmLanguage.json',
  'source.json.comments': 'JSONC.tmLanguage.json',
  'source.objc': 'objective-c.tmLanguage.json',
  'source.swift': 'swift.tmLanguage.json',
  'source.perl.6': 'perl6.tmLanguage.json',
  'source.powershell': 'powershell.tmLanguage.json',
  'source.python': 'MagicPython.tmLanguage.json',
  'source.regexp.python': 'MagicRegExp.tmLanguage.json',
  'source.rust': 'rust.tmLanguage.json',
  'source.scala': 'scala.tmlanguage.json',
  'source.shell': 'shell-unix-bash.tmLanguage.json',
  'source.tsx': 'TypeScriptReact.tmLanguage.json',
  'source.cs': 'csharp.tmLanguage.json',
  'source.fsharp': 'fsharp.tmLanguage.json',
  'source.dart': 'Dart.tmLanguage',
  'source.erlang': 'Erlang.tmLanguage',
  'source.elixir': 'Elixir.tmLanguage',
  'source.postscript': 'Postscript.tmLanguage',
  'source.c++': 'c.tmLanguage.json',
  'source.js.jquery': 'javascript.tmLanguage.json',
  'source.asm': 'rgbds-asm.tmLanguage',
  'source.x86': 'Assembly (x86).tmLanguage',
  'source.x86_64': 'Assembly (x86).tmLanguage',
  'source.arm': 'ARM.tmLanguage',
  'source.cpp.embedded.macro': 'cpp.embedded.macro.tmLanguage.json',
  'source.glsl': 'GLSL.tmLanguage',
  'source.applescript': 'applescript.tmLanguage.json',
  'source.graphql': 'GraphQL.tmLanguage',
  'source.js.jsx': 'JavaScript (JSX).tmLanguage',
  'source.toml': 'TOML.tmLanguage',
} as const;

export type GrammarScope = keyof typeof GRAMMAR_SCOPE_NAME_MAP;

export const GRAMMAR_PLIST = [
  'source.sass',
  'source.postcss',
  'source.js.regexp',
  'source.livescript',
  'source.dart',
  'source.erlang',
  'source.elixir',
  'source.postscript',
  'source.stylus',
  'source.asm',
  'source.x86',
  'source.x86_64',
  'source.arm',
  'source.glsl',
  'source.graphql',
  'source.js.jsx',
  'source.toml',
  'text.haml',
  'text.html.javadoc',
  'text.html.textile',
  'text.dart-doccomments',
  'text.elixir',
];
