export const SUFFIX_MAP = {
  HTML: 'html',
  Haml: 'haml',
  Markdown: 'md',
  Pug: 'pug',
  CSS: 'css',
  Less: 'less',
  SCSS: 'scss',
  Sass: 'sass',
  Stylus: 'styl',
  PostCSS: 'postcss',
  JavaScript: 'js',
  Babel: 'js',
  TypeScript: 'ts',
  CoffeeScript: 'coffee',
  LiveScript: 'mlx',
  Vue: 'vue',
} as const;
