name: CI-Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_call:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup environment
        uses: './.github/actions/setup-environment'

      - name: echo env
        run: |
          echo "$VITE_CDN_API_URL"
          echo "$JOB_ENV"
        env:
          VITE_CDN_API_URL: ${{ secrets.VITE_CDN_API_URL }}
          JOB_ENV: 123456789

      - name: run unit test
        run: pnpm test:unit
        env:
          VITE_CDN_API_URL: ${{ secrets.VITE_CDN_API_URL }}
